"""
Multi-Agent Weather Simulation — inspired by MiroFish (666ghj/MiroFish)

Simulation runs in two modes, selected automatically per-cycle:

  SCENARIO MODE (default, SCENARIO_SPECULATION=true):
    Phase 1 — Morgan (Scenario Architect) generates 2-3 explicit future weather
              scenarios with probability weights.
    Phase 2 — 4 analysts each estimate P(YES | scenario_i) independently.
    Phase 3 — River (Bayesian Synthesizer) computes the final weighted probability:
              P(YES) = Σ P(scenario_i) × mean_analyst_P(YES|scenario_i)
    Result: sharper probability estimates, especially when models disagree.
    Cost:   ~6 API calls vs 12 for classic debate (faster + cheaper).

  CLASSIC DEBATE MODE (fallback / SCENARIO_SPECULATION=false):
    4 analysts debate for SIM_ROUNDS rounds; consensus = average final estimates.
    Used when scenario mode is disabled or Morgan fails to produce valid scenarios.

Learning integration (both modes):
  - Lessons from ExperienceMemory injected into every analyst system prompt.
  - Persona biases augmented with learned calibration updates at runtime.
"""
from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Optional

from config import (
    MAX_AGENTS_PER_SIM, SIM_ROUNDS,
    PERSONA_WEIGHTING, SCENARIO_SPECULATION, SCENARIO_THRESHOLD_F,
)
from llm_client import LLMClient
from weather_data import CityForecast

if TYPE_CHECKING:
    from learning.memory import ExperienceMemory

logger = logging.getLogger(__name__)

# ─── Analyst Personas (base — augmented at runtime by learned lessons) ───────

ANALYST_PERSONAS = [
    {
        "name": "Alex (ECMWF Purist)",
        "bias": "strongly trust ECMWF over GFS; underweight short-range observations",
        "style": "data-driven, concise, references ensemble spread",
    },
    {
        "name": "Jordan (Mesoscale Expert)",
        "bias": "prioritise local METAR obs and urban heat-island effects",
        "style": "detailed, references micro-climate patterns",
    },
    {
        "name": "Sam (Climatologist)",
        "bias": "weights historical climatological anomalies; sceptical of single-model extremes",
        "style": "cautious, references 30-year normals",
    },
    {
        "name": "Casey (Contrarian)",
        "bias": "questions model consensus; looks for under-priced tail risks",
        "style": "provocative, challenges assumptions",
    },
]


# ─── Data classes ─────────────────────────────────────────────────────────────

@dataclass
class WeatherScenario:
    """One branch of the future weather envelope generated by Morgan."""
    name: str
    probability: float          # P(this scenario occurs); all scenarios sum to 1.0
    expected_temp_f: float      # best estimate of max temp if this scenario plays out
    description: str            # one-sentence meteorological mechanism

    def __str__(self) -> str:
        return (f'"{self.name}" (P={self.probability:.0%}): '
                f'expected {self.expected_temp_f:.1f}°F — {self.description}')


@dataclass
class AgentTurn:
    agent_name: str
    round_num: int
    message: str
    probability_estimate: Optional[float] = None   # global estimate (classic mode)
    conditional_probs: Optional[list[float]] = None  # P(YES|scenario_i) (scenario mode)
    provider: str = ""
    model: str = ""


@dataclass
class SimulationResult:
    city: str
    target_date: str
    bucket_low: float
    bucket_high: float
    consensus_probability: float
    model_spread_f: Optional[float]
    turns: list[AgentTurn] = field(default_factory=list)
    confidence_level: str = "medium"   # low / medium / high
    scenarios: list[WeatherScenario] = field(default_factory=list)
    scenario_reasoning: str = ""       # River's qualitative assessment

    @property
    def signal_strength(self) -> float:
        """Distance of consensus probability from 0.5 — higher = stronger signal."""
        return abs(self.consensus_probability - 0.5)

    @property
    def used_scenario_mode(self) -> bool:
        return len(self.scenarios) > 0


# ─── Simulation engine ────────────────────────────────────────────────────────

class WeatherSimulation:
    """
    Runs a multi-agent simulation for a city + temperature bucket.

    With scenario speculation enabled (default):
      Morgan → 4 analysts → River → weighted P(YES)

    Without scenario speculation:
      Classic 4-agent debate for SIM_ROUNDS rounds.
    """

    def __init__(
        self,
        experience_memory: Optional["ExperienceMemory"] = None,
        sim_rounds: Optional[int] = None,
    ) -> None:
        self._clients = LLMClient.ensemble()
        self._client = self._clients[0]
        self._exp_memory = experience_memory
        self._sim_rounds = sim_rounds if sim_rounds is not None else SIM_ROUNDS
        self._use_scenarios = SCENARIO_SPECULATION

    # ─── Shared helpers ───────────────────────────────────────────────────────

    def _bucket_desc(self, lo: float, hi: float) -> str:
        if lo == float("-inf") and hi == float("inf"):
            return "any temperature"
        if lo == float("-inf"):
            return f"below {hi:.0f}°F"
        if hi == float("inf"):
            return f"above {lo:.0f}°F"
        return f"{lo:.0f}°F–{hi:.0f}°F"

    def _forecast_block(self, forecast: CityForecast) -> str:
        return (
            f"  ECMWF max: {f'{forecast.ecmwf.temp_f:.1f}°F' if forecast.ecmwf else 'N/A'}\n"
            f"  GFS max:   {f'{forecast.gfs.temp_f:.1f}°F' if forecast.gfs else 'N/A'}\n"
            f"  METAR obs: {f'{forecast.metar.temp_f:.1f}°F' if forecast.metar else 'N/A'}\n"
            f"  Consensus: {f'{forecast.consensus_temp_f:.1f}°F' if forecast.consensus_temp_f else 'N/A'}\n"
            f"  Model spread: {f'{forecast.model_spread_f:.1f}°F' if forecast.model_spread_f else 'N/A'}"
        )

    def _learned_context(self, city: str) -> str:
        if self._exp_memory is None:
            return ""
        lessons = self._exp_memory.lessons_for_city(city, top_n=6)
        if not lessons:
            return ""
        lines = ["\n=== LEARNED LESSONS FROM PAST PREDICTIONS ==="]
        for l in lessons:
            rel = (f"{l.reliability_score:.0%}"
                   if (l.times_validated + l.times_violated) > 0 else "new")
            lines.append(f"  [{l.category}] (reliability={rel}) {l.content}")
        lines.append("=== END LESSONS ===\nApply these where relevant.")
        return "\n".join(lines)

    def _persona_updates(self, persona_name: str) -> str:
        if self._exp_memory is None:
            return ""
        cal = [
            l for l in self._exp_memory.lessons_by_category("agent_calibration")
            if persona_name.split()[0].lower() in l.content.lower()
        ]
        if not cal:
            return ""
        updates = [f"  • {l.content.replace(f'[{persona_name.split()[0]} persona update] ', '')}"
                   for l in cal[-3:]]
        return "\nCalibration updates from experience:\n" + "\n".join(updates)

    def _personas(self) -> list[dict]:
        personas = list(ANALYST_PERSONAS)
        if self._exp_memory is not None:
            personas.extend(self._exp_memory.dynamic_personas)
        return personas[:MAX_AGENTS_PER_SIM]

    def _client_for_persona(self, idx: int) -> LLMClient:
        return self._clients[idx % len(self._clients)]

    def _persona_weight(self, persona_name: str) -> float:
        if not PERSONA_WEIGHTING or self._exp_memory is None:
            return 1.0
        return self._exp_memory.persona_weight(persona_name)

    def _weighted_mean(self, values: list[tuple[str, float]]) -> float:
        if not values:
            return 0.5
        weighted_sum = 0.0
        total_weight = 0.0
        for persona_name, value in values:
            weight = self._persona_weight(persona_name)
            weighted_sum += value * weight
            total_weight += weight
        return weighted_sum / total_weight if total_weight > 0 else sum(v for _, v in values) / len(values)

    def _extract_json(self, text: str) -> Optional[dict]:
        """Extract the first JSON object from a response (tolerates surrounding prose)."""
        match = re.search(r'\{.*\}', text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                return None
        return None

    # ─── Phase 1: Morgan — Scenario generation ────────────────────────────────

    def _morgan_system_prompt(
        self,
        forecast: CityForecast,
        bucket_low: float,
        bucket_high: float,
        target_date: str,
    ) -> str:
        bucket = self._bucket_desc(bucket_low, bucket_high)
        spread = forecast.model_spread_f or 0.0
        n_scenarios = 3 if spread >= 4.0 else 2
        return f"""You are Morgan (Scenario Architect), a senior meteorological scenario planner.
Your role: generate {n_scenarios} DISTINCT, physically plausible future weather scenarios for the city and date below.
Each scenario must represent a meaningfully different atmospheric evolution
(e.g. different frontal timing, ridge strength, sea breeze vs. inland heating, convective vs. stratiform).

City: {forecast.city}
Date: {target_date}
Temperature bucket under analysis: {bucket}
Model data:
{self._forecast_block(forecast)}

Rules:
- {n_scenarios} scenarios, mutually exclusive, collectively exhaustive.
- "probability" values must sum exactly to 1.0.
- "expected_temp_f" is your best-estimate max temperature IF that scenario occurs.
- "description" is one sentence explaining the meteorological mechanism.

Respond ONLY with valid JSON — no prose before or after:
{{
  "scenarios": [
    {{
      "name": "3-6 word scenario label",
      "probability": 0.45,
      "expected_temp_f": 72.0,
      "description": "One sentence meteorological mechanism."
    }}
  ]
}}"""

    def _parse_scenarios(self, text: str) -> list[WeatherScenario]:
        data = self._extract_json(text)
        if not data or "scenarios" not in data:
            return []
        raw = data["scenarios"]
        if not isinstance(raw, list) or len(raw) < 2:
            return []
        scenarios = []
        for s in raw:
            try:
                scenarios.append(WeatherScenario(
                    name=str(s["name"]),
                    probability=float(s["probability"]),
                    expected_temp_f=float(s["expected_temp_f"]),
                    description=str(s["description"]),
                ))
            except (KeyError, TypeError, ValueError):
                continue
        if not scenarios:
            return []
        # Normalise probabilities to sum to 1.0
        total = sum(s.probability for s in scenarios)
        if total <= 0:
            return []
        for s in scenarios:
            s.probability /= total
        return scenarios

    def _run_morgan(
        self,
        forecast: CityForecast,
        bucket_low: float,
        bucket_high: float,
        target_date: str,
    ) -> list[WeatherScenario]:
        try:
            text = self._client.text(
                max_tokens=600,
                system=self._morgan_system_prompt(forecast, bucket_low, bucket_high, target_date),
                messages=[{"role": "user", "content": "Generate the scenarios now."}],
            )
            scenarios = self._parse_scenarios(text)
            if scenarios:
                logger.info(
                    "Morgan → %d scenarios for %s: %s",
                    len(scenarios), forecast.city,
                    " | ".join(f"{s.name}({s.probability:.0%})" for s in scenarios),
                )
            return scenarios
        except Exception as exc:
            logger.warning("Morgan failed for %s: %s", forecast.city, exc)
            return []

    # ─── Phase 2: Conditional analyst debate ──────────────────────────────────

    def _analyst_conditional_prompt(
        self,
        persona: dict,
        scenarios: list[WeatherScenario],
        forecast: CityForecast,
        bucket_low: float,
        bucket_high: float,
        target_date: str,
    ) -> str:
        bucket = self._bucket_desc(bucket_low, bucket_high)
        scenario_block = "\n".join(
            f"  Scenario {i+1} (P={s.probability:.0%}): {s.name}\n"
            f"    Expected temp: {s.expected_temp_f:.1f}°F\n"
            f"    Mechanism: {s.description}"
            for i, s in enumerate(scenarios)
        )
        learned = self._learned_context(forecast.city)
        updates = self._persona_updates(persona["name"])
        return f"""You are {persona['name']}, a weather analyst.
Analytical bias: {persona['bias']}{updates}
Style: {persona['style']}

City: {forecast.city} | Date: {target_date}
Temperature bucket under analysis: {bucket}
Model data:
{self._forecast_block(forecast)}
{learned}
The following {len(scenarios)} weather scenarios have been identified:
{scenario_block}

For EACH scenario, estimate the conditional probability that the actual daily maximum temperature
will fall within {bucket}.  Apply your specific analytical bias and expertise.

Respond ONLY with valid JSON:
{{
  "conditional_probs": [<prob for scenario 1>, <prob for scenario 2>{''.join(', <prob for scenario ' + str(i+1) + '>' for i in range(2, len(scenarios)))}],
  "reasoning": "<1-2 sentences: most important factor driving your estimates>"
}}"""

    def _parse_conditional_probs(self, text: str, n: int) -> list[float]:
        data = self._extract_json(text)
        if not data or "conditional_probs" not in data:
            return [0.5] * n
        raw = data["conditional_probs"]
        if not isinstance(raw, list) or len(raw) != n:
            return [0.5] * n
        try:
            return [max(0.0, min(1.0, float(p))) for p in raw]
        except (TypeError, ValueError):
            return [0.5] * n

    def _run_conditional_analysts(
        self,
        scenarios: list[WeatherScenario],
        forecast: CityForecast,
        bucket_low: float,
        bucket_high: float,
        target_date: str,
    ) -> list[AgentTurn]:
        personas = self._personas()
        turns: list[AgentTurn] = []
        for idx, persona in enumerate(personas):
            prompt = self._analyst_conditional_prompt(
                persona, scenarios, forecast, bucket_low, bucket_high, target_date
            )
            client = self._client_for_persona(idx)
            try:
                text = client.text(
                    max_tokens=500,
                    system=prompt,
                    messages=[{"role": "user", "content": "Provide your conditional probability estimates."}],
                )
            except Exception as exc:
                logger.error("Analyst %s conditional call failed: %s", persona["name"], exc)
                text = json.dumps({"conditional_probs": [0.5] * len(scenarios), "reasoning": "API error"})

            cond_probs = self._parse_conditional_probs(text, len(scenarios))
            # Derive a single global estimate as weighted sum (for backward compat)
            global_p = sum(s.probability * p for s, p in zip(scenarios, cond_probs))

            turn = AgentTurn(
                agent_name=persona["name"],
                round_num=1,
                message=text,
                probability_estimate=global_p,
                conditional_probs=cond_probs,
                provider=client.provider,
                model=client.model,
            )
            turns.append(turn)
            logger.debug(
                "  %s conditional probs=%s → global_p=%.3f",
                persona["name"],
                [f"{p:.2f}" for p in cond_probs],
                global_p,
            )
        return turns

    # ─── Phase 3: River — Bayesian synthesis ──────────────────────────────────

    def _river_system_prompt(
        self,
        scenarios: list[WeatherScenario],
        turns: list[AgentTurn],
        computed_p: float,
        forecast: CityForecast,
        bucket_low: float,
        bucket_high: float,
    ) -> str:
        bucket = self._bucket_desc(bucket_low, bucket_high)

        # Build analyst × scenario table
        header = "         " + "  ".join(f"Sc{i+1}({s.probability:.0%})" for i, s in enumerate(scenarios))
        rows = []
        for t in turns:
            if t.conditional_probs:
                probs_str = "  ".join(f"{p:.2f}         "[: 6 + len(f"Sc{i+1}({scenarios[i].probability:.0%})")] for i, p in enumerate(t.conditional_probs))
                rows.append(f"  {t.agent_name[:20]:<20} {probs_str}")
        table = header + "\n" + "\n".join(rows)

        # Per-scenario mean across analysts
        scenario_means = []
        for i, s in enumerate(scenarios):
            probs = [
                (t.agent_name, t.conditional_probs[i])
                for t in turns
                if t.conditional_probs and i < len(t.conditional_probs)
            ]
            mean = self._weighted_mean(probs) if probs else 0.5
            scenario_means.append(mean)

        contrib_lines = "\n".join(
            f"  Scenario {i+1} '{s.name}': P(scenario)={s.probability:.0%} × "
            f"mean_P(YES|sc)={scenario_means[i]:.3f} → contribution={s.probability * scenario_means[i]:.4f}"
            for i, s in enumerate(scenarios)
        )

        return f"""You are River (Bayesian Synthesizer), a statistical weather forecast expert.
Your role: assess the quality and confidence of a scenario-weighted probability estimate.

City: {forecast.city} | Bucket: {bucket}

Scenario breakdown:
{contrib_lines}

Analyst conditional probability estimates:
{table}

Pre-computed P(YES) = {computed_p:.4f}  [= Σ P(scenario_i) × mean_analyst_P(YES|scenario_i)]

Tasks:
1. Assess analyst AGREEMENT per scenario (high spread = lower confidence).
2. Assess scenario PROBABILITY uncertainty (are the scenario weights reasonable?).
3. Decide overall confidence: "high" (analysts agree, scenarios well-separated),
   "medium" (moderate disagreement), "low" (high uncertainty or analysts diverge).
4. Suggest a small adjustment if the computed estimate looks biased (max ±0.05).

Respond ONLY with valid JSON:
{{
  "confidence": "high" | "medium" | "low",
  "reasoning": "2-3 sentences: key sources of uncertainty and why you chose this confidence level",
  "suggested_adjustment": <float, −0.05 to +0.05, 0.0 if estimate looks correct>
}}"""

    def _run_river(
        self,
        scenarios: list[WeatherScenario],
        turns: list[AgentTurn],
        computed_p: float,
        forecast: CityForecast,
        bucket_low: float,
        bucket_high: float,
    ) -> tuple[str, float, str]:
        """Returns (confidence_level, adjusted_probability, reasoning)."""
        try:
            text = self._client.text(
                max_tokens=400,
                system=self._river_system_prompt(
                    scenarios, turns, computed_p, forecast, bucket_low, bucket_high
                ),
                messages=[{"role": "user", "content": "Synthesise the forecast now."}],
            )
            data = self._extract_json(text)
            if data:
                confidence = data.get("confidence", "medium")
                if confidence not in ("high", "medium", "low"):
                    confidence = "medium"
                adj = float(data.get("suggested_adjustment", 0.0))
                adj = max(-0.05, min(0.05, adj))  # hard-clamp
                final_p = max(0.02, min(0.98, computed_p + adj))
                reasoning = str(data.get("reasoning", ""))
                logger.info(
                    "River → confidence=%s adj=%+.3f p: %.3f→%.3f | %s",
                    confidence, adj, computed_p, final_p, reasoning[:80],
                )
                return confidence, final_p, reasoning
        except Exception as exc:
            logger.warning("River failed for %s: %s", forecast.city, exc)
        return "medium", computed_p, ""

    # ─── Scenario-mode entry point ────────────────────────────────────────────

    def _run_with_scenarios(
        self,
        forecast: CityForecast,
        bucket_low: float,
        bucket_high: float,
        target_date: str,
    ) -> SimulationResult:
        # Phase 1 — Morgan
        scenarios = self._run_morgan(forecast, bucket_low, bucket_high, target_date)
        if not scenarios:
            raise ValueError("Morgan produced no valid scenarios")

        # Phase 2 — Conditional analyst estimates
        turns = self._run_conditional_analysts(
            scenarios, forecast, bucket_low, bucket_high, target_date
        )

        # Compute weighted probability in Python (no API call needed)
        scenario_mean_probs: list[float] = []
        for i in range(len(scenarios)):
            analyst_probs = [
                t.conditional_probs[i]
                for t in turns
                if t.conditional_probs and i < len(t.conditional_probs)
            ]
            mean = sum(analyst_probs) / len(analyst_probs) if analyst_probs else 0.5
            scenario_mean_probs.append(mean)

        computed_p = sum(
            s.probability * scenario_mean_probs[i]
            for i, s in enumerate(scenarios)
        )
        computed_p = max(0.02, min(0.98, computed_p))

        # Phase 3 — River synthesis and confidence assessment
        confidence, final_p, reasoning = self._run_river(
            scenarios, turns, computed_p, forecast, bucket_low, bucket_high
        )

        logger.info(
            "Scenario simulation %s %s [%.0f–%.0f°F] → p=%.3f (%s) via %d scenarios",
            forecast.city, target_date, bucket_low, bucket_high,
            final_p, confidence, len(scenarios),
        )
        return SimulationResult(
            city=forecast.city,
            target_date=target_date,
            bucket_low=bucket_low,
            bucket_high=bucket_high,
            consensus_probability=final_p,
            model_spread_f=forecast.model_spread_f,
            turns=turns,
            confidence_level=confidence,
            scenarios=scenarios,
            scenario_reasoning=reasoning,
        )

    # ─── Classic debate mode (fallback) ──────────────────────────────────────

    def _build_classic_system_prompt(
        self,
        persona: dict,
        forecast: CityForecast,
        bucket_low: float,
        bucket_high: float,
        target_date: str,
    ) -> str:
        bucket = self._bucket_desc(bucket_low, bucket_high)
        learned = self._learned_context(forecast.city)
        updates = self._persona_updates(persona["name"])
        return f"""You are {persona['name']}, a weather analyst with the following profile:
- Analytical bias: {persona['bias']}{updates}
- Communication style: {persona['style']}

You are participating in a structured forecast debate for:
  City: {forecast.city}
  Date: {target_date}
  Temperature bucket under analysis: {bucket}

Available forecast data:
{self._forecast_block(forecast)}
{learned}
After your analysis, you MUST end your response with exactly this JSON line (no other JSON):
{{"p": <float 0.0–1.0>}}
where p is YOUR probability estimate that the actual max temperature will fall in {bucket}.
"""

    def _extract_probability(self, text: str) -> Optional[float]:
        match = re.search(r'\{"p":\s*([\d.]+)\}', text)
        if match:
            return max(0.0, min(1.0, float(match.group(1))))
        return None

    def _run_classic_debate(
        self,
        forecast: CityForecast,
        bucket_low: float,
        bucket_high: float,
        target_date: str,
    ) -> SimulationResult:
        personas = self._personas()
        turns: list[AgentTurn] = []
        histories: dict[str, list[dict]] = {p["name"]: [] for p in personas}
        debate_transcript: list[str] = []

        for round_num in range(1, self._sim_rounds + 1):
            for idx, persona in enumerate(personas):
                context_block = (
                    "\n\n--- Debate so far ---\n"
                    + "\n".join(debate_transcript[-8:])
                    + "\n--- End debate ---\n\nNow provide YOUR analysis for this round."
                    if debate_transcript else "Begin your initial analysis."
                )
                histories[persona["name"]].append({
                    "role": "user",
                    "content": f"Round {round_num}. {context_block}",
                })
                client = self._client_for_persona(idx)
                try:
                    text = client.text(
                        max_tokens=400,
                        system=self._build_classic_system_prompt(
                            persona, forecast, bucket_low, bucket_high, target_date
                        ),
                        messages=histories[persona["name"]],
                    )
                except Exception as exc:
                    logger.error("Agent %s round %d failed: %s", persona["name"], round_num, exc)
                    text = '{"p": 0.5}'

                histories[persona["name"]].append({"role": "assistant", "content": text})
                prob = self._extract_probability(text)
                turns.append(AgentTurn(
                    agent_name=persona["name"],
                    round_num=round_num,
                    message=text,
                    probability_estimate=prob,
                    provider=client.provider,
                    model=client.model,
                ))
                debate_transcript.append(f"[{persona['name']} R{round_num}]: {text[:300]}")
                logger.debug("  %s R%d → p=%.2f", persona["name"], round_num, prob or -1)

        final_probs = [
            t.probability_estimate
            for t in turns
            if t.round_num == self._sim_rounds and t.probability_estimate is not None
        ]
        final_named_probs = [
            (t.agent_name, t.probability_estimate)
            for t in turns
            if t.round_num == self._sim_rounds and t.probability_estimate is not None
        ]
        consensus = self._weighted_mean(final_named_probs) if final_named_probs else 0.5
        spread = (max(final_probs) - min(final_probs)) if len(final_probs) >= 2 else 1.0
        confidence = "high" if spread < 0.10 else ("medium" if spread < 0.25 else "low")

        logger.info(
            "Classic simulation %s %s [%.0f–%.0f°F] → p=%.3f (%s)",
            forecast.city, target_date, bucket_low, bucket_high, consensus, confidence,
        )
        return SimulationResult(
            city=forecast.city,
            target_date=target_date,
            bucket_low=bucket_low,
            bucket_high=bucket_high,
            consensus_probability=consensus,
            model_spread_f=forecast.model_spread_f,
            turns=turns,
            confidence_level=confidence,
        )

    # ─── Main entry point ─────────────────────────────────────────────────────

    def run(
        self,
        forecast: CityForecast,
        bucket_low: float,
        bucket_high: float,
        target_date: str,
    ) -> SimulationResult:
        """
        Run the simulation for one city + bucket.
        Uses scenario mode if enabled and model spread exceeds threshold,
        otherwise falls back to classic multi-round debate.
        """
        spread = forecast.model_spread_f or 0.0
        use_scenarios = (
            self._use_scenarios
            and spread >= SCENARIO_THRESHOLD_F
        )

        if use_scenarios:
            try:
                return self._run_with_scenarios(forecast, bucket_low, bucket_high, target_date)
            except Exception as exc:
                logger.warning(
                    "Scenario mode failed for %s (%s), falling back to classic debate",
                    forecast.city, exc,
                )

        return self._run_classic_debate(forecast, bucket_low, bucket_high, target_date)
